import React, { useState } from 'react';
import Head from "next/head";
import Image from "next/image";
import Navbar from 'components/navbar';
import { useRouter } from 'next/router';
import { primaryColor } from 'styles/global';
import CustomButton from "components/customButton";
import RegisterModal from 'components/registerModal';
import {
  HomePageStyleHeader,
  AmazingFeatureStyle,
  InvoicePlaceHolderImage,
  HomePageStyleContainer,
  SoftwareInvoicingStyle,
  SmartInvoicingStyle,
  SaveTimeStyle,
  FooterStyle
} from "styles/homepage";

const Index = () => {
  const route = useRouter()
  const [registerModal, setRegisterModal] = useState(false)

  const navigateHandler = () => {
    setRegisterModal(true)
  }

  return (
    <React.Fragment>
      <Head>
        <title>Zee Invoices</title>
        <link rel='icon' href='/favicon.ico' />
        <meta name='description' content='Generated by create next app' />
      </Head>
      <HomePageStyleContainer>
        <Navbar />

        <HomePageStyleHeader>
          <div className='header'>
            <div className='header_content container'>
              <div className='header_content_heading'>
                <p>
                  Easy invoice builder, made for EVERYONE
                </p>
                <h1>
                  Invoice that help businesses get paid faster
                </h1>
              </div>
              <div className='header_content_btn'>
                <CustomButton
                  lh='28px'
                  fs='22px'
                  radius="10px"
                  color='#FFFFFF'
                  p={'16px 30px'}
                  bg={primaryColor}
                  title='Create Invoice'
                  clicked={navigateHandler}
                  border="2px solid #3F4DE1"
                />
              </div>
            </div>
          </div>
        </HomePageStyleHeader>

        <InvoicePlaceHolderImage>
          <Image
            fill
            alt='InvoicePlaceholder.png'
            src='/images/InvoicePlaceholder.png'
            className='invoicePlaceHolderImage_img'
          />
        </InvoicePlaceHolderImage>

        <AmazingFeatureStyle>
          <div className="amazingfeature_heading container" >
            <h1>Amazing Feature</h1>
          </div>
          <div className="amazingfeature_cards container" >
            <div className="amazingfeature_cards_card" >
              <div className="amazingfeature_cards_card_icon" >
                <Image
                  width='60'
                  height='60'
                  alt='easyToUse'
                  src='/images/easyToUse.png'
                  className='amazingfeature_cards_card_icon_img'
                />
              </div>
              <div className="amazingfeature_cards_card_detail" >
                <h1>Easy to use</h1>
                <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
              </div>
            </div>
            <div className="amazingfeature_cards_card" >
              <div className="amazingfeature_cards_card_icon" >
                <Image
                  width='60'
                  height='60'
                  alt='customColor'
                  src='/images/customColor.png'
                  className='amazingfeature_cards_card_icon_img'
                />
              </div>
              <div className="amazingfeature_cards_card_detail" >
                <h1>Custome color</h1>
                <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
              </div>
            </div>
            <div className="amazingfeature_cards_card" >
              <div className="amazingfeature_cards_card_icon" >
                <Image
                  width='60'
                  height='60'
                  alt='freeGenerate'
                  src='/images/freeGenerate.png'
                  className='amazingfeature_cards_card_icon_img'
                />
              </div>
              <div className="amazingfeature_cards_card_detail" >
                <h1>Free  Generate</h1>
                <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
              </div>
            </div>
          </div>
        </AmazingFeatureStyle>

        <SoftwareInvoicingStyle>
          <div className="softwareInvoicing_main" >
            <div className="softwareInvoicing_main_content container" >
              <div className="softwareInvoicing_main_content_img" >
                <Image
                  width={512}
                  height={483}
                  alt='customInvoice'
                  src='/images/customInvoice.svg'
                  className="softwareInvoicing_main_content_img_myimg"
                />
              </div>
              <div className="softwareInvoicing_main_content_detail" >
                <h1>How Software Invoicing can help small business</h1>
                <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. </p>
                <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. </p>
                <div className="softwareInvoicing_main_content_detail_btn" >
                  <CustomButton title='Generate Invoice' bg={primaryColor} color='#FFFFFF' p={'18px 30px'} fs='22px' lh='28px' />
                </div>
              </div>
            </div>
          </div>
        </SoftwareInvoicingStyle>

        <SmartInvoicingStyle>
          <div className="smartinvoincing_content container" >
            <div className="smartinvoincing_content_heading" >
              <h1>Smart Invoicing for small businesses & freelancers</h1>
            </div>
            <div className="smartinvoincing_content_cards" >
              <div className="smartinvoincing_content_cards_card" >
                <div className="smartinvoincing_content_cards_card_icon" >
                  <Image
                    width='39'
                    height='39'
                    alt='customIcon'
                    src='/images/customIcon.svg'
                    className="softwareInvoicing_main_content_img_myimg"
                  />
                </div>
                <div className="smartinvoincing_content_cards_card_detail" >
                  <h1>Convert quote into invoice in single click</h1>
                  <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
                </div>
              </div>
              <div className="smartinvoincing_content_cards_card" >
                <div className="smartinvoincing_content_cards_card_icon" >
                  <Image
                    width='39'
                    height='39'
                    alt='customIcon'
                    src='/images/customIcon.svg'
                    className="softwareInvoicing_main_content_img_myimg"
                  />
                </div>
                <div className="smartinvoincing_content_cards_card_detail" >
                  <h1>Easy to use</h1>
                  <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
                </div>
              </div>
              <div className="smartinvoincing_content_cards_card" >
                <div className="smartinvoincing_content_cards_card_icon" >
                  <Image
                    width='39'
                    height='39'
                    alt='customIcon'
                    src='/images/customIcon.svg'
                    className="softwareInvoicing_main_content_img_myimg"
                  />
                </div>
                <div className="smartinvoincing_content_cards_card_detail" >
                  <h1>Easy to use</h1>
                  <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
                </div>
              </div>
              <div className="smartinvoincing_content_cards_card" >
                <div className="smartinvoincing_content_cards_card_icon" >
                  <Image
                    width='39'
                    height='39'
                    alt='customIcon'
                    src='/images/customIcon.svg'
                    className="softwareInvoicing_main_content_img_myimg"
                  />
                </div>
                <div className="smartinvoincing_content_cards_card_detail" >
                  <h1>Send Invoice And qoute</h1>
                  <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
                </div>
              </div>
              <div className="smartinvoincing_content_cards_card" >
                <div className="smartinvoincing_content_cards_card_icon" >
                  <Image
                    width='39'
                    height='39'
                    alt='customIcon'
                    src='/images/customIcon.svg'
                    className="softwareInvoicing_main_content_img_myimg"
                  />
                </div>
                <div className="smartinvoincing_content_cards_card_detail" >
                  <h1>Send Invoice And qoute</h1>
                  <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
                </div>
              </div>
              <div className="smartinvoincing_content_cards_card" >
                <div className="smartinvoincing_content_cards_card_icon" >
                  <Image
                    width='39'
                    height='39'
                    alt='customIcon'
                    src='/images/customIcon.svg'
                    className="softwareInvoicing_main_content_img_myimg"
                  />
                </div>
                <div className="smartinvoincing_content_cards_card_detail" >
                  <h1>save your customer details</h1>
                  <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document</p>
                </div>
              </div>
            </div>
          </div>
        </SmartInvoicingStyle>

        <SaveTimeStyle>
          <div className="saveTime_content container">
            <div className="saveTime_content_detail">
              <h1><span>Save time and get</span><span>paid fast</span> </h1>
              <p>Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.
                Lorem ipsum may be used as a placeholder before final copy is available.</p>
              <p>
                Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.
              </p>
            </div>
            <div className="saveTime_content_image">
              <Image
                width={630}
                height={372}
                alt='userinvoice'
                src='/images/userinvoice.png'
                className="saveTime_content_image_img"
              />
            </div>
          </div>
        </SaveTimeStyle>

        <FooterStyle>
          <div className="footer_content">
            <div className="footer_content_detail container">
              <Image
                width='128'
                height='75'
                alt='zeeinvoices-footerIcon'
                className="footer_content_detail_img"
                src='/images/zeeinvoices-footerIcon.svg'
              />
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla est purus, ultrices in porttitor in, accumsan non quam. Nam consectetur porttitor rhoncus. Curabitur eu est et leo feugiat auctor vel quis lorem.</p>
            </div>
            <div className="footer_content_bottom container">
              <p>
                <span>Terms of Service</span>
                <span>Privacy Policy </span>
              </p>
              <h6>© 2022 ZeeInvoices. All rights reserved.</h6>
              <div className="footer_content_bottom_socialIcons">
                <Image
                  width='39'
                  height='39'
                  alt='linkedin'
                  src='/images/linkedin.svg'
                  className="footer_content_bottom_socailIcon_img"
                />
                <Image
                  width='39'
                  height='39'
                  alt='Facebook'
                  src='/images/Facebook.svg'
                  className="footer_content_bottom_socailIcon_img"
                />
                <Image
                  width='39'
                  height='39'
                  alt='Insta'
                  src='/images/insta.svg'
                  className="footer_content_bottom_socailIcon_img"
                />
                <Image
                  width='39'
                  height='39'
                  alt='Youtube'
                  src='/images/Youtube.svg'
                  className="footer_content_bottom_socailIcon_img"
                />
              </div>
            </div>
          </div>
        </FooterStyle>
      </HomePageStyleContainer>

      <RegisterModal openModal={registerModal} closeModal={setRegisterModal} />
    </React.Fragment>
  )
}

export default Index